### ISSUE TITLE
initialUri doesn't seem to be working when calling openDirectory

### ISSUE THREAD

**Issue by brandon-watkins-avcrm** [flutter-cavalry/saf_util#3]
I am running my app on device with Android 10 installed.

When passing in an `initialUri` it is not opening the correct directory. I noticed this on a fresh install its opening the Internal Storage directory.

Examples I have tried:

Regular path: `DJI/com.dji.industry.pilot/FlightRecord`
A URI: `content://com.android.externalstorage.documents/tree/primary%3ADJI%2Fcom.dji.industry.pilot%2FFlightRecord`

If you navigate to the folder manually, each time you ask for the permission it will go to the last directory you chose... but the first time it doesn't work.

The URI above is correct because I have confirmed when you navigate manually to the directory and click Allow Access this is the URI returned from openDirectory.

Please let me know if I am doing something wrong here.

Thanks in advance.

**Comment by brandon-watkins-avcrm** [comment]
```
/// Convert Directory path to URI String
String makeUriString({String path = "", bool isTreeUri = false}) {
  String uri = "";
  String base =
      "content://com.android.externalstorage.documents/tree/primary%3A";
  String documentUri = "/document/primary%3A" +
      path.replaceAll("/", "%2F").replaceAll(" ", "%20");
  if (isTreeUri) {
    uri = base + path.replaceAll("/", "%2F").replaceAll(" ", "%20");
  } else {
    var pathSegments = path.split("/");
    var fileName = pathSegments[pathSegments.length - 1];
    var directory = path.split("/$fileName")[0];
    uri = base +
        directory.replaceAll("/", "%2F").replaceAll(" ", "%20") +
        documentUri;
  }
  return uri;
}
```

I had a look at how the original saf dart package was doing this and they have a helpful function which converts a path to a correct Uri. After adding this into my project it is now opening the correct initialUri :)

**Comment by mgenware** [comment]
I can reproduce it on both Flutter and native kotlin projects. It seems to be working as expected. I've updated the example project to allow setting an initial URI for quick testing. Try this:

- open folder A
- go to some sub folders let's say A -> B
- copy B's URI and go back to main page
- set B's URI as initial URI
- click 'Open'. it should open folder B, which is not the previous location

So it seems to me SAF only allows setting an initial URI within your permission scope or it will open the last URI. The code you posted requires a path instead of a URI, SAF APIs should be URI only :)
